export const siteConfig = {
  name: "Tan Le",
  title: "Software Engineer",
  description:
    "Tan Le’s portfolio — software engineering, full-stack development, and AI-powered applications.",
  accentColor: "#1d4ed8",
  social: {
    email: "letan101104@gmail.com",
    linkedin: "https://www.linkedin.com/in/tanle004/",
    twitter: "",
    github: "https://github.com/LTan-101104/",
  },
  aboutMe:
    "I’m Tan Le, a software engineer with a B.S. in Computer Science from the University of Massachusetts Amherst. My experience spans multi-agent automation infrastructure, full-stack applications, and data science. I’ve built resilient AI workflows at Magical, streamlined financial applications at Matson Money, and developed tools to analyze GPU utilization at UMass. I love building things, exploring data, and connecting with people to learn and solve problems together. I’m currently looking for software engineering and data roles where I can contribute and keep growing.",
  skills: [
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "SQL",
    "C++",
    "C",
    "C#",
    "Google Gemini API",
    "Vercel AI SDK",
    "Hugging Face Transformers",
    "Multi-Agent Systems",
    "Next.js",
    "Hono",
    "GraphQL",
    "Express.js",
    "Flask",
    "Java Spring Boot",
    "ASP.NET",
    "Drizzle",
    "PostgreSQL",
    "SQL Server",
    "MongoDB",
    "Redis",
    "Docker",
    "Temporal",
    "Git",
    "GitHub Actions",
    "VS Code",
    "IntelliJ",
    "Jupyter Notebook",
    "AWS",
    "Postman",
  ],
  projects: [
    {
      name: "HazardHub",
      description:
        "A mobile-first platform for crowdsourced road-hazard reporting and safety-based routing. Combines geospatial search and SOS features with Gemini image classification and community validation.",
      link: "",
      skills: [
        "Next.js",
        "React",
        "Spring Boot",
        "MongoDB",
        "REST API",
        "Docker",
        "Google Gemini API",
      ],
    },
    {
      name: "Autocomplete Service",
      description:
        "An extensible autocomplete service supporting 10 résumé fields for an AI-powered autofill system. Uses Redis/RediSearch prefix caching and concurrency-safe popularity scoring to improve autocomplete speed by over 50%.",
      link: "",
      skills: ["Python", "FastAPI", "Elasticsearch", "Redis", "Docker", "MongoDB"],
    },
    {
      name: "Aarti App",
      description:
        "A women’s rights educational mobile app developed for Vijay Foundation Trust, featuring interactive quizzes and a web admin dashboard for managing content.",
      link: "",
      skills: ["Express.js", "MongoDB", "Next.js", "React Native"],
    },
  ],
  experience: [
    {
      company: "Magical",
      logo: "magical_logo.png",
      title: "Software Engineer",
      dateRange: "Jun - Sep 2026",
      bullets: [
        "Engineered durable runtime infrastructure for a multi-agent automation platform using Temporal, Next.js, and AWS, enabling safe retries and full workflow observability",
        "Built a database-backed LLM model registry with Node.js and Drizzle, replacing hardcoded model references and routing Temporal retries to fallback models to withstand provider outages and model deprecations",
        "Shipped import/export for Data Stores, the shared state layer for automation, enabling users to reuse existing state across workflows and reducing manual configuration time by 70%",
      ],
    },
    {
      company: "Matson Money",
      logo: "matson_money_logo.png",
      title: "Software Engineer Intern",
      dateRange: "Sep - Dec 2025",
      bullets: [
        "Designed, developed, and maintained financial-management and internal-operations applications in an Agile workflow",
        "Engineered REST APIs and updated database schemas using ASP.NET and SQL Server to streamline electronic document and signature workflows across financial advisor and investor portals, reducing paperwork processing time by 50%",
        "Integrated the Contentful API with React.js to build reusable, custom-styled components for a content management system, enhancing the marketing-branding workflow and reducing content development cycle time by 60%",
      ],
    },
    {
      company: "UMass Center for Data Science / UMass Math REU",
      logo: "UMass_Amherst_logo.svg.webp",
      title: "Data Science Intern",
      dateRange: "Jun - Aug 2025",
      bullets: [
        "Designed and implemented a Python package to identify underutilized GPU resources across 1,400+ GPUs at the Massachusetts Unity high-performance computing center",
        "Optimized a SQL/Pandas pipeline to preprocess data and calculate statistical metrics across 10M+ jobs and 2M+ users, improving analysis speed by 30%",
        "Applied weighted VRAM-efficiency metrics, PCA, and K-Means clustering to identify the 15% most underutilized GPU users, generating usage reports and visualizations to guide targeted customer outreach",
        "Implemented GitHub Actions and Pytest CI with 95% test coverage, strengthening pipeline reliability and error handling",
      ],
    },
  ],
  education: [
    {
      school: "University of Massachusetts Amherst",
      logo: "UMass_Amherst_logo.svg.webp",
      degree: "Bachelor of Science in Computer Science",
      dateRange: "May 2026",
      achievements: [
        "GPA: 3.9",
        "Dean’s List, Fall 2022 - Spring 2026",
        "UMass Chancellor’s Award Scholarship",
        "Relevant coursework: Data Structures & Algorithms, Machine Learning, Database Systems, Distributed Operating Systems",
      ],
    },
  ],
};
